# Build ai_tools.pp from ai_tools.te + ai_tools.fc.
#
#   make            # -> ai_tools.pp
#   make clean
#
# Wraps the system refpolicy development Makefile (from selinux-policy-devel:
#   sudo dnf install selinux-policy-devel). install-selinux.sh invokes this.

include /usr/share/selinux/devel/Makefile
